import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Configure your database
config :gut, Gut.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "gut_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :gut, GutWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4043")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "5JcM3fF/hZ6T1rok2w2j1uaDP0AyD8/JLaYRvcFLMOOsJN1aoaRhmhUL90WDieX2",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:gut, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:gut, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :gut, GutWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/gut_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :gut,
  dev_routes: true,
  token_signing_secret: "dZOFJWGdgXEvo/9zKze4fFsm5JbQU6Kt",
  sessionize_main_url: System.get_env("SESSIONIZE_MAIN_URL"),
  sessionize_speaker_email_url: System.get_env("SESSIONIZE_SPEAKER_EMAIL_URL")

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :gut, Gut.Mailer, from_email: "noreply@example.com"
