defmodule Gut.Repo.Migrations.AddNotHappeningToSponsors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sponsors) do
      add :not_happening, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:sponsors) do
      remove :not_happening
    end
  end
end
