defmodule Gut.Repo.Migrations.AddSponsors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :role, :text, null: false, default: "user"
    end

    create table(:sponsors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :outreach, :text
      add :responded, :boolean, null: false, default: false
      add :interested, :boolean, null: false, default: false
      add :confirmed, :boolean, null: false, default: false
      add :sponsorship_level, :text
      add :logos_received, :boolean, null: false, default: false
      add :announced, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:sponsors)

    alter table(:users) do
      remove :role
    end
  end
end
