defmodule Gut.Repo.Migrations.RemoveInvitesAddActivatedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists table(:invites)

    alter table(:users) do
      add :activated_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:users) do
      remove :activated_at
    end

    create table(:invites, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :email, :citext, null: false
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :accepted, :boolean, null: false, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end
end
