defmodule Gut.Repo.Migrations.AddUniqueRoomTimeslotConstraint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:workshops, [:workshop_room_id, :workshop_timeslot_id],
             name: "workshops_unique_room_timeslot_index"
           )
  end

  def down do
    drop_if_exists unique_index(:workshops, [:workshop_room_id, :workshop_timeslot_id],
                     name: "workshops_unique_room_timeslot_index"
                   )
  end
end
