defmodule Gut.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :role, :text, default: "staff"
    end

    execute "UPDATE users SET role = 'staff' WHERE role = 'user'"
    execute "UPDATE users SET role = 'staff' WHERE role = 'admin'"

    alter table(:sponsors) do
      add :user_id,
          references(:users,
            column: :id,
            name: "sponsors_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:invites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :accepted, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:invites)

    drop constraint(:sponsors, "sponsors_user_id_fkey")

    alter table(:sponsors) do
      remove :user_id
    end

    alter table(:users) do
      modify :role, :text, default: "user"
    end
  end
end
