defmodule Gut.Repo.Migrations.AddWorkshopBlasts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workshop_blasts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :body, :text, null: false
      add :sent_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workshop_id,
          references(:workshops,
            column: :id,
            name: "workshop_blasts_workshop_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:workshop_blasts, [:workshop_id])
  end

  def down do
    drop_if_exists index(:workshop_blasts, [:workshop_id])

    drop constraint(:workshop_blasts, "workshop_blasts_workshop_id_fkey")

    drop table(:workshop_blasts)
  end
end
