defmodule Gut.Repo.Migrations.AddSurveys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:surveys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "draft"
      add :sent_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workshop_id,
          references(:workshops,
            column: :id,
            name: "surveys_workshop_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:surveys, [:workshop_id], name: "surveys_unique_workshop_survey_index")

    create table(:survey_responses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :survey_id,
          references(:surveys,
            column: :id,
            name: "survey_responses_survey_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "survey_responses_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:survey_responses, [:survey_id, :user_id],
             name: "survey_responses_unique_response_index"
           )

    create table(:survey_questions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :prompt, :text, null: false
      add :question_type, :text, null: false, default: "single_line"
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :survey_id,
          references(:surveys,
            column: :id,
            name: "survey_questions_survey_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:survey_question_options, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :label, :text, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :survey_question_id,
          references(:survey_questions,
            column: :id,
            name: "survey_question_options_survey_question_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:survey_answers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :value, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :survey_response_id,
          references(:survey_responses,
            column: :id,
            name: "survey_answers_survey_response_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :survey_question_id,
          references(:survey_questions,
            column: :id,
            name: "survey_answers_survey_question_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:survey_answers, [:survey_response_id, :survey_question_id],
             name: "survey_answers_unique_answer_per_question_index"
           )
  end

  def down do
    drop constraint(:survey_answers, "survey_answers_survey_response_id_fkey")

    drop constraint(:survey_answers, "survey_answers_survey_question_id_fkey")

    drop_if_exists unique_index(:survey_answers, [:survey_response_id, :survey_question_id],
                     name: "survey_answers_unique_answer_per_question_index"
                   )

    drop table(:survey_answers)

    drop constraint(:survey_question_options, "survey_question_options_survey_question_id_fkey")

    drop table(:survey_question_options)

    drop constraint(:survey_questions, "survey_questions_survey_id_fkey")

    drop table(:survey_questions)

    drop constraint(:survey_responses, "survey_responses_survey_id_fkey")

    drop constraint(:survey_responses, "survey_responses_user_id_fkey")

    drop_if_exists unique_index(:survey_responses, [:survey_id, :user_id],
                     name: "survey_responses_unique_response_index"
                   )

    drop table(:survey_responses)

    drop constraint(:surveys, "surveys_workshop_id_fkey")

    drop_if_exists unique_index(:surveys, [:workshop_id],
                     name: "surveys_unique_workshop_survey_index"
                   )

    drop table(:surveys)
  end
end
