defmodule Gut.Repo.Migrations.AddSessionizeIdToWorkshops do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workshops) do
      add :sessionize_id, :text
    end
  end

  def down do
    alter table(:workshops) do
      remove :sessionize_id
    end
  end
end
