defmodule Gut.Repo.Migrations.AddWorkshopManagement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workshops, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :limit, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workshop_room_id, :uuid
      add :workshop_timeslot_id, :uuid
    end

    create table(:workshop_timeslots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :start, :utc_datetime, null: false
      add :end, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:workshop_speakers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workshop_id,
          references(:workshops,
            column: :id,
            name: "workshop_speakers_workshop_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :speaker_id,
          references(:speakers,
            column: :id,
            name: "workshop_speakers_speaker_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:workshop_speakers, [:workshop_id, :speaker_id],
             name: "workshop_speakers_unique_workshop_speaker_index"
           )

    create table(:workshop_rooms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:workshops) do
      modify :workshop_room_id,
             references(:workshop_rooms,
               column: :id,
               name: "workshops_workshop_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :workshop_timeslot_id,
             references(:workshop_timeslots,
               column: :id,
               name: "workshops_workshop_timeslot_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:workshop_rooms) do
      add :name, :text, null: false
      add :limit, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:workshop_participations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workshop_id,
          references(:workshops,
            column: :id,
            name: "workshop_participations_workshop_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :workshop_participant_id, :uuid, null: false
    end

    create table(:workshop_participants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:workshop_participations) do
      modify :workshop_participant_id,
             references(:workshop_participants,
               column: :id,
               name: "workshop_participations_workshop_participant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:workshop_participations, [:workshop_id, :workshop_participant_id],
             name: "workshop_participations_unique_participation_index"
           )

    alter table(:workshop_participants) do
      add :name, :text, null: false
      add :phone_number, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "workshop_participants_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:workshop_participants, "workshop_participants_user_id_fkey")

    alter table(:workshop_participants) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :phone_number
      remove :name
    end

    drop_if_exists unique_index(
                     :workshop_participations,
                     [:workshop_id, :workshop_participant_id],
                     name: "workshop_participations_unique_participation_index"
                   )

    drop constraint(
           :workshop_participations,
           "workshop_participations_workshop_participant_id_fkey"
         )

    alter table(:workshop_participations) do
      modify :workshop_participant_id, :uuid
    end

    drop table(:workshop_participants)

    drop constraint(:workshop_participations, "workshop_participations_workshop_id_fkey")

    drop table(:workshop_participations)

    alter table(:workshop_rooms) do
      remove :updated_at
      remove :inserted_at
      remove :limit
      remove :name
    end

    drop constraint(:workshops, "workshops_workshop_room_id_fkey")

    drop constraint(:workshops, "workshops_workshop_timeslot_id_fkey")

    alter table(:workshops) do
      modify :workshop_timeslot_id, :uuid
      modify :workshop_room_id, :uuid
    end

    drop table(:workshop_rooms)

    drop_if_exists unique_index(:workshop_speakers, [:workshop_id, :speaker_id],
                     name: "workshop_speakers_unique_workshop_speaker_index"
                   )

    drop constraint(:workshop_speakers, "workshop_speakers_workshop_id_fkey")

    drop constraint(:workshop_speakers, "workshop_speakers_speaker_id_fkey")

    drop table(:workshop_speakers)

    drop table(:workshop_timeslots)

    drop table(:workshops)
  end
end
