defmodule Gut.Repo.Migrations.AddHotelFieldsToSpeakers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:speakers) do
      add :room_number, :text
      add :confirmed_with_hotel, :text, default: "unconfirmed"
      add :sharing_with, :text
      add :wants_early_checkin, :boolean, default: false
      add :double_bed, :boolean, default: false
      add :special_requests, :text
      add :hotel_notes, :text
    end
  end

  def down do
    alter table(:speakers) do
      remove :hotel_notes
      remove :special_requests
      remove :double_bed
      remove :wants_early_checkin
      remove :sharing_with
      remove :confirmed_with_hotel
      remove :room_number
    end
  end
end
