defmodule Gut.Repo.Migrations.AddRequiredToSurveyQuestions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:survey_questions) do
      add :required, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:survey_questions) do
      remove :required
    end
  end
end
