defmodule Gut.Repo.Migrations.AddSurveyFkIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:survey_questions) do
      modify :survey_id, :uuid
    end

    create index(:survey_questions, [:survey_id])

    alter table(:survey_question_options) do
      modify :survey_question_id, :uuid
    end

    create index(:survey_question_options, [:survey_question_id])

    alter table(:survey_answers) do
      modify :survey_question_id, :uuid
    end

    create index(:survey_answers, [:survey_question_id])
  end

  def down do
    drop_if_exists index(:survey_answers, [:survey_question_id])

    alter table(:survey_answers) do
      modify :survey_question_id, :uuid
    end

    drop_if_exists index(:survey_question_options, [:survey_question_id])

    alter table(:survey_question_options) do
      modify :survey_question_id, :uuid
    end

    drop_if_exists index(:survey_questions, [:survey_id])

    alter table(:survey_questions) do
      modify :survey_id, :uuid
    end
  end
end
