defmodule Gut.Repo.Migrations.CascadeDeleteWorkshopAssociations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:workshop_speakers, "workshop_speakers_workshop_id_fkey")

    alter table(:workshop_speakers) do
      modify :workshop_id,
             references(:workshops,
               column: :id,
               name: "workshop_speakers_workshop_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:workshop_participations, "workshop_participations_workshop_id_fkey")

    alter table(:workshop_participations) do
      modify :workshop_id,
             references(:workshops,
               column: :id,
               name: "workshop_participations_workshop_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:workshop_participations, "workshop_participations_workshop_id_fkey")

    alter table(:workshop_participations) do
      modify :workshop_id,
             references(:workshops,
               column: :id,
               name: "workshop_participations_workshop_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:workshop_speakers, "workshop_speakers_workshop_id_fkey")

    alter table(:workshop_speakers) do
      modify :workshop_id,
             references(:workshops,
               column: :id,
               name: "workshop_speakers_workshop_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
