defmodule Gut.Repo.Migrations.AddSpeakerContractAndBooking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:speakers) do
      add :plus_one, :boolean, default: false
      add :days_covered, :bigint
      add :contract_approved_at, :utc_datetime_usec
      add :contract_approved_git_sha, :text
    end
  end

  def down do
    alter table(:speakers) do
      remove :contract_approved_git_sha
      remove :contract_approved_at
      remove :days_covered
      remove :plus_one
    end
  end
end
