defmodule Gut.Repo.Migrations.AddAmountAndLikelihoodToSponsors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sponsors) do
      add :amount_eur, :bigint
      add :likelihood, :bigint
    end
  end

  def down do
    alter table(:sponsors) do
      remove :likelihood
      remove :amount_eur
    end
  end
end
