defmodule Gut.Repo.Migrations.AddMissingFromSessionize do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workshops) do
      add :missing_from_sessionize, :boolean, default: false
    end

    alter table(:speakers) do
      add :missing_from_sessionize, :boolean, default: false
    end
  end

  def down do
    alter table(:speakers) do
      remove :missing_from_sessionize
    end

    alter table(:workshops) do
      remove :missing_from_sessionize
    end
  end
end
